global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Avalonia.Threading;
global using DailyMealPlannerExtended.Services;
global using Serilog;
